@hostname = http://localhost:3001

GET {{hostname}} HTTP/1.1
Authorization: Basic carlos:password

###

GET {{hostname}} HTTP/1.1
Authorization: Basic admin supersecret

###

PUT {{hostname}}/login HTTP/1.1
Authorization: Basic carlos password
content-type: application/json

{
    "email": "carlos",
    "password": "password"
}
